version: '3'

services:
  wordpress:
    image: wordpress
    ports:
      - 80:80
    # restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass
    depends_on:
      - mysql
    links:
      - mysql
    volumes:
      - ./wp-content/plugins:/var/www/html/wp-content/uploads
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
  mysql:
    image: mysql:5.7
    ports:
      - 3306:80
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sample
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass
    volumes:
      - db-data:/var/lib/mysql
      - ./db-data:/docker-entrypoint-initdb.d
volumes:
  db-data:
    driver: local
